from . import hr_hospital_person_mixin
from . import hr_hospital_diagnosis
from . import hr_hospital_doctor_speciality
from . import hr_hospital_doctor
from . import hr_hospital_patient
from . import hr_hospital_visit
from . import hr_hospital_disease
from . import hr_hospital_disease_type
from . import res_partner
